services:
  cashflow-postgres:
    container_name: cashflow-postgres
    image: postgres
    environment:
      - POSTGRES_DB=cashflow_dev
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    volumes:
      - ./volume/postgres:/var/lib/postgresql/data

  cashflow-pgadmin:
    container_name: cashflow-pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@email.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    restart: unless-stopped
    depends_on:
      - cashflow-postgres